### ISSUE TITLE
Not all supported languages show up in list

### ISSUE THREAD

**Issue by boaz001** [Bryanx/byheart#1]
When choosing the front or back language for a stack of cards I cannot select my language (Dutch).

The dropdown only lists the following (scrolling does not reveal more) languages:
![63761da7-a395-4308-8431-64b1519ef419](https://user-images.githubusercontent.com/3184497/61950861-83fc5300-afaf-11e9-9f22-e5d6922a3f28.png)

Version: 2.0.3

**Comment by Bryanx** [comment]
Oops, looking into it.
