### ISSUE TITLE
CSV import makes random characters

### ISSUE THREAD

**Issue by MrFunEGUY** [Bryanx/byheart#6]
When I import an excel files with terms in one file and definitions in the other, it doesn't work. It just comes up with random characters like when you open a file in a text editor that isn't really a text file.

**Comment by Bryanx** [comment]
Hi, thanks for trying my app. When importing / exporting special characters from Excel you have to select Unicode / UTF-8 to maintain the characters. You also have to follow this format:

front | back
:-------------------------:|:-------------------------:
term | definition

**Comment by MrFunEGUY** [comment]
It was probably the encoding. Thanks.
